<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7UA5NPA" name="自动化测试用例" tests="1" failures="0" timestamp="1 Jan 2020 06:38:55 GMT" time="0.786" errors="0">
  <testcase name="test_case" time="0.771" classname="com.Auto_Test.Case.Test_Case_AutoInterface">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : expected [Post] but found [Set] in method : .test_case(Test_Case_AutoInterface:62)
	at com.Auto_Test.Case.Test_Case_AutoInterface.test_case(Test_Case_AutoInterface.java:62)
]]>
    </failure>
  </testcase> <!-- test_case -->
</testsuite> <!-- 自动化测试用例 -->
